import "./globals.css";
import Header from "./Header";
import Main from "./Main";
import Footer from "./Footer";
import { M_PLUS_Rounded_1c } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#ffffff",
};

export const mplus = M_PLUS_Rounded_1c({ weight: "400", subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={mplus.className}>
      <head />
      <body>
        <Header />
        <Main>{children}</Main>
        <Footer />
      </body>
    </html>
  );
}
